---
title: "Cosas útiles Genome Browser"
author: "Alejandro Paniagua de Pedro"
date: "7/7/2022"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = F)
```

## Cosas utiles UCSC Genome Browser (GB)

Podemos subir track directamete al GB utilizando la opción add track,
sin embargo, para anotaciones muy grandes u otros archivos como
covertura de short-reads esto no es posible. Para subir este tipo de
archivos hay que crear un Track Hub (TH) o, en caso de que el genoma de
referencia no este disponible en GB, un Assembly Hub (AH), que además de
incluir las anotaciones incluirá la propia secuencia del genoma. Las
principales págianas de ayuda para ambos tipos de Hub se pueden
encontrar en:

-   Track hubs:
    <https://genome.ucsc.edu/goldenPath/help/hgTrackHubHelp.html>

-   Assembly hubs: <http://genomewiki.ucsc.edu/index.php/Assembly_Hubs>

Me centro en los AH ya que el modo de subir la anotaciones a ambos es la
misma. Este tipo de hubs tienen una organización jerárquica, un ejemplo
se puede encontrar en:
<https://genome-test.gi.ucsc.edu/~hiram/hubs/Plants/>

### hub.txt

El archivo más importante de un AH es el hub.txt, la url hasta este
archivo es la que se utiliza linkear el AH al GB. Estearchivo contiene
la siguiente información:

```{bash}
hub hubName
shortLabel genome
longLabel Comment describing this hub contents
genomesFile genomes.txt
email contactEmail@institution.edu
descriptionUrl aboutHub.html
```

### genomes.txt

Es el archivo con la información de los genomas que hay en el AH:

```{bash }
genome genomeName
trackDb genomeName/trackDb.txt Archivo con la información de los tracks (anotaciones)
groups genomeName/groups.txt Grupos en los que se organizan los tracks
description description
twoBitPath genomeName/genomeName.2bit Secuencia del genoma en formato 2bit
organism organismo
defaultPos chrXX:1-15000
orderKey 4800
scientificName Trichechus manatus latirostris
htmlPath genomeName/description.html
```

#### 2bit file

Archivo de secuencia del genome en formato 2bit. Se genera a partir del
genoma en formato fasta.

```{bash}
faToTwoBit genomeName.fa genomeName.2bit
```

#### chrom sizes file

Archivo para la generación de los Big files. Se genera a partir del 2bit
files.

```{bash}
twoBitInfo genomeName.2bit stdout | sort -k2rn > genomeName.chrom.sizes
```

### group.txt

Sirve para definir los grupos en los que se pueden incluir los diversos
tracks. Las pestañitas que salen abajo de la representación del genoma.
Se pueden incluir varios grupos separados por un enter. Ejemplo:

```{bash}
name nombre
label nombre para mostrar en el GB
priority 2
defaultIsClosed 0
```

### trackDB.txt

Es el fichero que contiene la información de todos los tracks
(anotaciones)

```{bash}
track uniqueNameNoSpacesOrDots
group uno de los grupos definidos en el archivo group.txt # opcional
type track_type # bigBed 12
bigDataUrl track_data_url
shortLabel label 17 chars
longLabel long label up to 80 chars
visibiltiy hide/dense/squish/pack/full # Como de compacto aparece el track
searchIndex field,field2 # genralmente name opcional
searchTrix path/to/.ix/file # opcional
```

Cuando hacemos alguna modificación en un track esta tarda un tiempo en
hacer efecto. Si añdimos udcTimeout=5& a la url de nuestro hub esta se
recarga de manera inmediata. Si se está haciendo muchso cambios puede
resultar útil dejar esta opción activada, pero una vez finalizados los
cambios es reconmendable desactivarla ya que reduce el rendimiento.

#### track files

Los tracks son las anotaciones que se cargan en el GB. Los tipos de
ficheros que se pueden utilizar son: bigBed, bigBarChart, bigGenePred,
bigNarrowPeak, bigPsl, bigChain, bigInteract, bigMaf, bigWig, BAM, CRAM,
HAL, hic o VCF.

Generalmente vamos a tener las anotaciones en formato GTF. Estos tracks
pueden añadirse desde la pestaña de add tracks y subirse directamente a
la web de UCSC, sin embargo, también es posible incorporarlos en nuestro
AH. Puesto que el formato GTF no está directamente aceptado en el AH hay
que convertirlo en primer lugar a formato genePred.

```{bash}
./gtfToGenePred file.gtf file.genePred
```

Depués hay que convertir el archivo en formato genePred a formato bed y
ordenarlo:

```{bash}
./genePredToBed file.genePred file.bed12
LC_COLLATE=C sort -k1,1 -k2,2n file.bed12 > file.sorted.bed
```

Y finalmente convertimos el fichero de de bed a bigBed para lo cual se
necesita el archivo del tamaño de los cromosomas (chrom sizes file)

```{bash}
./bedToBigBed -extraIndex=name file.sorted.bed file.sizes file.bb
```

Opcionalmente es posible crear otros índices de búsqueda. Para ello se
utiliza el siguiente comando:

```{bash}
cat file.genePred | awk '{print $1, $12, $1}' > input.txt
ixIxx input.txt out.ix out.ixx
```

##### SJout.tabs

Los archivos SJout.tab son generados por el mapeador STAR cuando se
utiliza la opción --twopassmode. Este archivo no se puede convertir
directamente a bigBed. Para poder hacer esta conversión es necesario un
paso intermedio para convertir el fichero SJout.tab en formato bed:

```{bash}
awk 'BEGIN { OFS="\t"; str[0]="."; str[1]="+"; str[2]="-" } { print $1, $2-1, $3, "j_" NR, 1000, str[$4] }' SJ.out.tab > SJ.out.bed
```

El archivo de salida es un bed6, el cual debemos convertir a bigBed para
poder subirlo al UCSC GB:

```{bash}
LC_COLLATE=C sort -k1,1 -k2,2n SJ.out.bed > SJ.out.sorted.bed
./bedToBigBed SJ.out.sorted.bed file.sizes SJ.out.bb
```

##### BAM files

Los archivos BAM son archivos binarios de alineamientos. Son aceptamos
directamente por el UCSC GB. solamente es necesarios ordenarlos y
generar un índice.

```{bash}
samtools sort unsorted.bam complete_sorted.bam
samtools index complete_sorted.bam
```

La información de estos tracks en el trackDb es diferente de la de los
ficheros bigBed. En este caso toda la información debe de estar en la
misma linea y los campos deben estar separados por espacios. En el
siguiente ejempo están separados en filas para que se lea mejor pero
debería ir todo en la misma linea.

```{bash}
track type=bam bigDataUrl=http://...
    pairEndsByName=.  # si son pair end (vale poner cualquierr caracter)
    pairSearchRange=N # máxima distancia entre alineamientos pair-end
    bamColorMode=strand|gray|tag|off # metodo de colorear (por defecto strand)
    bamGrayMode=aliQual|baseQual|unpaired # coloreo en base a calidad
    bamColorTag=XX # tag que se utiliza para colorear
    minAliQual=N 
    showNames=on|off
    name=track_label 
    description=center_label 
    visibility=display_mode 
    priority=priority
    db=db 
    maxWindowToDraw=N 
    chromosomes=chr1,chr2,...
    doWiggle=on # Representar la densidad en lugar de las reads
```

### Programas útiles

bedToBigBed convierte un archivo en formato bed a BigBed faToTwoBit
permite convertir un archivo de formato fasta a 2bit genePredToBed
convierte un archivo en formato genePred a BED gtfToGenePred convertir
un archivo de formato gtf a formato genePred ixIxx crea un índice para
realizar búsquedas más rápidas twoBitInfo permite extaer información de
los archivos en formato 2bit. Se utiliza para generar los archivos de
chrom size

### Referencias

<https://groups.google.com/g/rna-star/c/dIw4JhXtb0o>
<https://physiology.med.cornell.edu/faculty/skrabanek/lab/angsd/lecture_notes/STARmanual.pdf>
